services:

  db:
    image: mysql:8.4
    container_name: barba_db
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: barba_db
    ports:
      - "3310:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - barba_net

  backend:
    build: ./backend
    container_name: barba_backend
    environment:
      DB_HOST: db
      DB_NAME: barba_db
      DB_USER: root
      DB_PASS: root123
    ports:
      - "8091:80"
    depends_on:
      - db
    networks:
      - barba_net

  frontend:
    build: ./frontend
    container_name: barba_frontend
    ports:
      - "8004:80"
    depends_on:
      - backend
    networks:
      - barba_net

volumes:
  db_data:

networks:
  barba_net:
